name: maison_moel
description: "MaisonMoel Project AP4"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_theme: ^6.5.4
  mobile_scanner: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/themeMoel.json
    - assets/
    - assets/images/
  fonts:
    - family: LibreBaskerville
      fonts:
        - asset: fonts/LibreBaskerville-Regular.ttf
        - asset: fonts/LibreBaskerville-Italic.ttf
          style: italic
        - asset: fonts/LibreBaskerville-Bold.ttf
          weight: 700